/* This file is auto-generated by Rake */

/* Build Host Info:
 * - Host Name: runner-zvqc8ky-project-50-concurrent-0
 * - Kernel Build: Linux version 5.15.0-116-generic (buildd@lcy02-amd64-036) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #126~20.04.1-Ubuntu SMP Mon Jul 1 15:40:07 UTC 2024
 * - Build Timestamp: 2025-02-14 14:42:10 +0000
 * - Ruby Version: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
 * - Rake Version: rake, version 13.0.3
 */

/*
 * Source Control Info:
 * - Submodule:
 *    b20379c9a5343039eaddec33e99c676fc002b6e2 emrun (b20379c)
 */

#ifndef __NUCLEI_SEGGER_RTL_RELEASE_H
#define __NUCLEI_SEGGER_RTL_RELEASE_H 1

#define __NUCLEI_SEGGER_RTL_RELEASE_COMMIT "a25fc19dd384abcaecf7b08182f803b8cd67d815"

#endif /* __NUCLEI_SEGGER_RTL_RELEASE_H */
